services:
  rowdy:
    image: "mcr.microsoft.com/devcontainers/go:1.20"
    container_name: rowdy
    hostname: rowdy
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - CONNSTR=postgresql://root@cockroach:26257/rowdy?sslmode=disable
      - DB=rowdy
    volumes:
      - .:${PWD}
    working_dir: ${PWD}
    depends_on:
      - cockroach
      - postgresql

  cockroach:
    image: cockroachdb/cockroach:v22.2.6
    command: start-single-node --insecure --store=type=mem,size=4GiB
    environment:
      - COCKROACH_DATABASE=rowdy
      - COCKROACH_USER=root

  cockroach-client:
    image: cockroachdb/cockroach:v22.2.6
    restart: "no"
    command:
      [
        "sql",
        "--insecure",
        "--url",
        "postgresql://cockroach"
      ]
    volumes:
      - ./roles:/cockroach/roles:ro
    depends_on:
      - cockroach

  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rowdy

  postgresql-client:
    image: postgres:15
    restart: "no"
    environment:
      - PGPASSWORD=root
    command: [ "psql", "-h", "postgresql", "-d", "rowdy" ]
    depends_on:
      - postgresql

  robotframework:
    image: madworx/robotframework-databaselibrary
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.robotframework
    entrypoint:
      [
        "/usr/local/bin/robot",
        "-P",
        ".",
        "-L",
        "DEBUG",
        "-d",
        "results/"
      ]
    volumes:
      - .:/app
    working_dir: /app/e2e_tests
    depends_on:
      - cockroach
