services:
  rowdy:
    image: "mcr.microsoft.com/devcontainers/go:1.20"
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - CONNSTR=postgresql://root@cockroach:26257/rowdy?sslmode=disable
      - DB=rowdy
    volumes:
      - ..:${PWD}

  cockroach:
    image: cockroachdb/cockroach:v22.2.6
    command: start-single-node --insecure --store=type=mem,size=4GiB
    ports:
      - "26257:26257"
    environment:
      - COCKROACH_DATABASE=rowdy
      - COCKROACH_USER=root
