name: Test and coverage

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start docker compose environment
        run: docker compose up -d

      - name: docker ps
        run: docker ps

      - name: Fixup git permission checking
        run: docker exec rowdy git config --global --add safe.directory ${PWD}

      - name: Fixup golang and cache directory for devcontainer
        run: docker exec rowdy sh -c 'mkdir /.cache && chmod -R 777 /go /.cache'

      - name: Run unit tests
        run: docker exec -u $(id -u) -w ${PWD} rowdy make test

      - name: Run e2e tests
        run: make coverage-e2e.out

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
