name: Test and coverage

on:
  push:
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Start docker compose environment
        run: docker compose up -d

      - name: docker ps
        run: docker ps 

      - name: Fixup git permission checking
        run: docker exec rowdy git config --global --add safe.directory ${PWD}

      - name: Run tests
        run: docker exec -w ${PWD} rowdy make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3